kind: pipeline
type: docker
name: commit

steps:
- name: test_lts
  image: node:10
  volumes:
    - name: modules_lts
      path: /drone/src/node_modules
  commands:
    - npm install
    - npm test

- name: test_latest
  image: node:12
  volumes:
    - name: modules_latest
      path: /drone/src/node_modules
  commands:
    - npm install
    - npm test

- name: publish
  image: node:12
  depends_on:
    - test_lts
    - test_latest
  commands:
    - echo "Ready for publishing"
  when:
    branch:
      - master

volumes:
- name: modules_lts
  temp: {}
- name: modules_latest
  temp: {}
